### ISSUE TITLE
Hidden dependency on Glassfish Jersey?

### ISSUE THREAD

**Issue by alaz** [codereligion/bugsnag-logback#8]
Here it is what I got on startup:

```
09:30:02,201 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [com.codereligion.bugsnag.logback.Appender]
09:30:02,224 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [BUGSNAG]
09:30:02,339 |-ERROR in ch.qos.logback.core.joran.spi.Interpreter@18:16 - RuntimeException in Action for tag [appender] java.lang.RuntimeException: java.lang.ClassNotFoundException: org.glassfish.jersey.client.JerseyClientBuilder
	at java.lang.RuntimeException: java.lang.ClassNotFoundException: org.glassfish.jersey.client.JerseyClientBuilder
	at 	at javax.ws.rs.client.ClientBuilder.newBuilder(ClientBuilder.java:103)
	at 	at javax.ws.rs.client.ClientBuilder.newClient(ClientBuilder.java:114)
	at 	at com.codereligion.bugsnag.logback.Sender.createClient(Sender.java:137)
	at 	at com.codereligion.bugsnag.logback.Sender.start(Sender.java:63)
	at 	at com.codereligion.bugsnag.logback.Appender.start(Appender.java:56)
	at 	at ch.qos.logback.core.joran.action.AppenderAction.end(AppenderAction.java:96)
	at 	at ch.qos.logback.core.joran.spi.Interpreter.callEndAction(Interpreter.java:317)
	at 	at ch.qos.logback.core.joran.spi.Interpreter.endElement(Interpreter.java:196)
	at 	at ch.qos.logback.core.joran.spi.Interpreter.endElement(Interpreter.java:182)
	at 	at ch.qos.logback.core.joran.spi.EventPlayer.play(EventPlayer.java:62)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:149)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:135)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:99)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:49)
```

**Comment by SierraGolf** [comment]
Nope, if you checkout the project you will see there is no dependency to jersey, actually it comes with jboss resteasy.

It must be from your project.

**Comment by alaz** [comment]
Hmm, weird.

Sorry for bothering
